## PyTorch 基础
- 学习目标：
1. Tensor操作：掌握Tensor的创建、索引、切片、变形（reshape）、广播等基本操作。
2. 自动求导（Autograd）：理解torch.autograd的工作原理，掌握backward()的使用。
3. 模型定义：学习如何使用torch.nn.Module定义神经网络，包括层（Layer）的定义和顺序模型（Sequential）的使用。
4. 优化器与损失函数：熟悉常用的优化器（如SGD、Adam）和损失函数（如交叉熵、MSE。

### Tensor操作

In [22]:
# 创建Tensor
import torch

# 创建一个未初始化的5x3矩阵
x = torch.empty(5, 3)
print(x)

# 创建一个随机初始化的5x3矩阵
x = torch.rand(5, 3)
print(x)

# 创建一个全0的5x3矩阵
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# 直接从数据创建Tensor
x = torch.tensor([5.5, 3])
print(x)

tensor([[-1.6305e+06,  9.3186e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0.1518, 0.6909, 0.3255],
        [0.2687, 0.8549, 0.6882],
        [0.6149, 0.4646, 0.2184],
        [0.5632, 0.3889, 0.8105],
        [0.3986, 0.5666, 0.0559]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


In [ ]:
# tensor 索引
x = torch.rand(5, 3)

# 访问第1行
print(x[1])

# 访问第1行第2列
print(x[1][2])

# 使用切片访问第1行到第3行
print(x[1:3])

# 使用切片访问第1列到第3列
print(x[:, 1:3])

tensor([0.0056, 0.1510, 0.3192])
tensor(0.3192)
tensor([[0.0056, 0.1510, 0.3192],
        [0.9880, 0.5651, 0.4452]])
tensor([[0.2922, 0.0046],
        [0.1510, 0.3192],
        [0.5651, 0.4452],
        [0.7584, 0.9527],
        [0.5202, 0.9274]])


In [25]:
# 使用reshape改变Tensor的形状
x = torch.rand(4, 4)
y = x.reshape(16)
z = x.reshape(-1, 8)  # -1表示自动计算该维度的大小
print("y:", y)
print("z:", z)

y: tensor([0.8667, 0.8576, 0.6768, 0.3228, 0.9768, 0.4070, 0.0441, 0.0695, 0.5628,
        0.2685, 0.6328, 0.1543, 0.5166, 0.9839, 0.2098, 0.2485])
z: tensor([[0.8667, 0.8576, 0.6768, 0.3228, 0.9768, 0.4070, 0.0441, 0.0695],
        [0.5628, 0.2685, 0.6328, 0.1543, 0.5166, 0.9839, 0.2098, 0.2485]])


In [30]:
# 广播机制允许不同形状的Tensor进行算术运算，只要它们的形状兼容。

x = torch.ones(5, 3)
y = torch.ones(1, 3)
print("x:", x)
print("y:", y)

z = torch.add(x, y)
print("z:", z)

x: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
y: tensor([[1., 1., 1.]])
z: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


### 自动求导

#### Autograd

In [31]:
# Autograd是PyTorch的自动求导引擎，它能够自动计算梯度，是PyTorch进行深度学习的基础。

# 创建一个Tensor，并设置requires_grad=True，表示需要计算梯度
x = torch.tensor(2.0, requires_grad=True)

# 进行一些操作
y = x**2 + 3

# 计算梯度
y.backward()

# 查看梯度
print(x.grad)

tensor(4.)
